services:
  redis:
    image: redis:alpine

  vote:
    build: 
      context: ./vote
    ports:
      - "5000:80"
    environment:
      SQL_SERVER: "${LOCAL_IP}"
      SQL_DATABASE: "MovieLens"
      SQL_USERNAME: "SA"
      SQL_PASSWORD: "StrongPass123!"
      REDIS_HOST: "redis"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
    environment:
      REDIS_HOST: "redis"
      KAFKA_HOST: "${LOCAL_IP}:9092"
    depends_on:
      - redis
  